name = "ml-hair-brain"
main = "src/index.ts"
compatibility_date = "2025-01-01"

kv_namespaces = [
  # Replace the id with the one Cloudflare gives you for the KV
  { binding = "EVENT_LOG_KV", id = "92f70cbd271e4f27a742c9faf280aecd" }
]

# Optional but nice
[vars]
ENVIRONMENT = "prod"
